#pragma once

#define JANUS_WIFI_SSID "YOUR_WIFI"
#define JANUS_WIFI_PASSWORD "YOUR_PASSWORD"
#define JANUS_NAS_URL "http://YOUR_NAS:PORT"
#define JANUS_NAS_TOKEN "YOUR_TOKEN"
#define JANUS_WORKER_NAME "YOUR_WORKER"
